version: "3.9"

services:
  app:
    build: .
    container_name: url-shortener
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - proxy
      - internal
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: pg-shortener
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-shortener
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata: