version: "3.9"

services:
  app:
    build: .
    container_name: url-shortener
    ports:
      - "${APP_PORT}:3000"        # External port APP_PORT maps to container port 3000 (Go app port)
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - proxy
      - internal
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: pg-shortener
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"        # External port DB_PORT maps to container port 5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis-shortener
    ports:
      - "6379:6379"              # Redis default port
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:

networks:
  proxy:
  internal: