name: CI/CD Pipeline

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

env:
  DOCKER_IMAGE: cemakan/url-shortener
  CONTAINER_NAME: url-shortener
  REGISTRY: docker.io

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi-arch)
        uses: docker/setup-qemu-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "cemakan"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with dev tag
        run: |
          docker build -t $DOCKER_IMAGE:dev .

      - name: Build and push latest image (main branch only)
        if: github.ref == 'refs/heads/main'
        run: |
          docker build -t $DOCKER_IMAGE:latest .
          docker push $DOCKER_IMAGE:latest

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Deploy to Production (SSH)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: 22
          script: |
            cd /opt/app/shortener
            docker compose pull
            docker compose up -d